#!/bin/zsh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
    VRSN=$(grep 'static let version' Sources/Agora-Video-UIKit/AgoraUIKit.swift | sed -e 's,.*\"\(.*\)\",\1,')
    pat="ref.+tags.+[0-9]+\.[0-9]+\.[0-9]+.*"
    if [[ $local_ref =~ $pat ]]; then
        TAG_VERSION=$(echo $local_ref | sed -e 's/refs\/tags\///g')
        if [ "$TAG_VERSION" != "$VRSN" ]; then
            echo "Invalid tag ${TAG_VERSION}, not matching AgoraUIKit.swift: ${VRSN}"
            exit 1
        fi
    fi
done

exit 0
