line_length: 
  ignores_comments: true
excluded:
  - Agora-*-Example
  - Sources/Agora-Video-UIKit/AgoraUIKit+MD5.swift
  - Sources/AgoraRtmControl/AgoraRtmController+RtmDelegateOverflows.swift
  - Sources/Agora-Video-UIKit/AgoraVideoViewer+RtcEngineDelegateOverflow.swift
  - .build
  - docc