# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Agora-UIKit-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Agora-UIKit-Example
  pod 'AgoraUIKit_iOS', :path => '../'
  pod 'AgoraRtmControl', :path => '../'
end
