# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Agora-SwiftUI-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Agora-UIKit-Example
  pod 'AgoraUIKit_iOS', :path => '../'

end
