name: "Pod Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - "*"

jobs:
  podlint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Pod Lint
      run: |
        pod lib lint --allow-warnings --skip-import-validation
      shell: bash
