on: push
name: "Pod Lint"
jobs:
  podlint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Pod Lint
      run: |
        pod lib lint --allow-warnings --skip-import-validation
      shell: bash
