name: "Pod Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - "*"

jobs:
  podlint:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pod Lint
      run: |
        pod lib lint AgoraUIKit_iOS.podspec --allow-warnings --skip-import-validation --include-podspecs='AgoraRtmControl_iOS.podspec';
        pod lib lint AgoraUIKit_macOS.podspec --allow-warnings --skip-import-validation --include-podspecs='AgoraRtmControl_macOS.podspec';
      shell: bash
